"use client";

import { usePathname } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../../components/ui/navbar";
import Footer from "../../components/ui/footer";
import "./globals.css";

// Importing Geist Sans and Geist Mono fonts from Google Fonts
import { Geologica, Figtree, Pixelify_Sans } from "next/font/google";

// Instantiating the fonts
const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const pixelifySans = Pixelify_Sans({
  variable: "--font-pixelify-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isStoryPage = pathname.startsWith("/pages/story");

  return (
    <html lang="en">
      <body
        className={` ${geologica.variable} ${figtree.variable} ${pixelifySans.variable} antialiased`}
      >
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {!isStoryPage && <Navbar />}
        {children}
        {!isStoryPage && <Footer />}
      </body>
    </html>
  );
}
